const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=file=>'/assets/cases/'+file;
const id=new URLSearchParams(location.search).get('id');
const main=document.getElementById('case-content');
const mediaGrid=items=>`<div class="media-grid">${items.map(([file,caption])=>`<figure><button type="button" data-image="${asset(file)}" data-caption="${escapeHTML(caption)}" aria-label="Ampliar: ${escapeHTML(caption)}"><img loading="lazy" src="${asset(file)}" alt="${escapeHTML(caption)}"><span aria-hidden="true">↗</span></button><figcaption>${escapeHTML(caption)}</figcaption></figure>`).join('')}</div>`;
try{const [projects,media]=await Promise.all([fetch('/cases.json').then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('/case-media.json').then(r=>{if(!r.ok)throw Error();return r.json()})]);const index=projects.findIndex(p=>p.id===id);if(index<0)throw Error('missing');const p=projects[index],m=media[id]||{},next=projects[(index+1)%projects.length];document.title=`${p.name} — Vinicius Romeiro`;document.querySelector('meta[name="description"]').content=p.title;
const lead=id==='paperx'?'Marca, website e aplicativo para conectar a rotina das assistências técnicas. Identidade visual, experiência de uso e arquitetura de produto desenvolvidas em conjunto, com integração de inteligência artificial aos fluxos de trabalho.':p.lead;
const features=p.features.map(([title,body])=>title.includes('13 agentes')?[title,'Estrutura de agentes desenvolvida para apoiar processos do negócio, conectando estratégia de marca, produto digital e automação com IA.']: [title,body]);
main.innerHTML=`<header class="case-title"><div class="case-breadcrumb"><span>TRABALHOS SELECIONADOS / 0${index+1}</span><span>INOVASYS × ROMEIRO</span></div><h1 class="${p.name.length>13?'long':''}">${escapeHTML(p.name)}</h1><p>${escapeHTML(p.title)}</p></header><div class="case-reel"><video controls muted loop playsinline preload="metadata" poster="${asset(id+'-v2.jpg')}" aria-label="Vídeo do projeto ${escapeHTML(p.name)}"><source src="${asset(id+'-v2.mp4')}" type="video/mp4"></video></div><div class="case-meta"><div><span>PROJETO</span><p>${escapeHTML(p.name)}</p></div><div><span>DISCIPLINAS</span><p>${escapeHTML(p.category)}</p></div><div><span>EXPLORAR</span>${p.website?`<a href="${escapeHTML(p.website)}" target="_blank" rel="noopener noreferrer">Visitar o projeto ↗</a>`:'<a href="#produto">Conhecer o produto ↓</a>'}</div></div><section class="case-story"><span class="eyebrow">01 / CONTEXTO</span><div><h2>Uma ideia.<br><em>Um universo inteiro.</em></h2><p>${escapeHTML(lead)}</p></div></section><section class="case-features"><span class="eyebrow">02 / O QUE CONSTRUÍMOS</span><h2>Da intenção<br><em>à experiência.</em></h2><div class="feature-grid">${features.map(([title,body],i)=>`<article><span>0${i+1}</span><h3>${escapeHTML(title)}</h3><p>${escapeHTML(body)}</p></article>`).join('')}</div></section>${m.brand?`<section class="media-section"><span class="eyebrow">IDENTIDADE / PROCESSO / APLICAÇÕES</span><div class="media-heading"><h2>${escapeHTML(m.brandTitle)}</h2><p>${escapeHTML(m.brandIntro)}</p></div>${mediaGrid(m.brand)}</section>`:''}${m.extra?`<section class="media-section"><span class="eyebrow">DIREÇÃO VISUAL / UNIVERSO DO PROJETO</span><div class="media-heading"><h2>${escapeHTML(m.extraTitle)}</h2><p>${escapeHTML(m.extraIntro)}</p></div>${m.worldVideo?`<video class="world-video" controls muted loop playsinline preload="metadata" poster="${asset('brand/tidle-cinematic.png')}" aria-label="Universo visual TIDLE"><source src="${asset(m.worldVideo)}" type="video/webm"></video>`:''}${mediaGrid(m.extra)}</section>`:''}<section class="media-section" id="produto"><span class="eyebrow">PRODUTO DIGITAL</span><div class="media-heading"><h2>Feito para<br><em>ser usado.</em></h2><p>O sistema visual ganha vida nas interfaces, na navegação e nos detalhes da experiência.</p></div>${mediaGrid([[p.image.split('/').pop(),`${p.name} — website`],...p.gallery])}</section><section class="case-next"><span>CONTINUE EXPLORANDO / PRÓXIMO PROJETO</span><a href="/projeto/?id=${next.id}">${escapeHTML(next.name)}<span>↗</span></a><div class="case-footer"><a href="/#trabalhos">← Todos os projetos</a><span>© ${new Date().getFullYear()} VINICIUS ROMEIRO</span><a href="/#contato">Vamos conversar ↗</a></div></section>`;
const dialog=document.querySelector('.lightbox');document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{dialog.querySelector('img').src=button.dataset.image;dialog.querySelector('img').alt=button.dataset.caption;dialog.querySelector('p').textContent=button.dataset.caption;dialog.showModal()}));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});if(!matchMedia('(prefers-reduced-motion:reduce)').matches){const video=main.querySelector('video');video.play().catch(()=>{})}
}catch(error){document.title='Projeto não encontrado — Vinicius Romeiro';main.innerHTML='<section class="case-title"><span class="eyebrow">PROJETO NÃO ENCONTRADO</span><h1>Vamos voltar?</h1><a class="text-link" href="/#trabalhos">Explorar todos os projetos ↗</a></section>'}
const caseMeta=document.querySelector('.case-meta');
if(caseMeta){
  document.querySelector('.case-story').id='contexto';
  document.querySelector('.case-features').id='entregas';
  const firstMedia=document.querySelector('.media-section');
  if(firstMedia&&!firstMedia.id)firstMedia.id='identidade';
  const indexNav=document.createElement('nav');indexNav.className='case-index';indexNav.setAttribute('aria-label','Seções do projeto');
  indexNav.innerHTML='<a href="#contexto">O projeto</a><a href="#entregas">Entregas</a>'+(document.getElementById('identidade')?'<a href="#identidade">Universo visual</a>':'')+'<a href="#produto">Interfaces</a>';
  caseMeta.after(indexNav);
}
