import React,{useEffect,useState} from 'react';
import {AbsoluteFill,Composition,Img,continueRender,delayRender,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
const projects=[
{id:'paperx',name:'PaperX',label:'IDENTIDADE / PRODUTO / IA',title:'O trabalho em campo, conectado.',main:'paperx.webp',detail:'paperx-app.webp',bg:'#d4deca'},
{id:'stival',name:'Stival',label:'ESTRATÉGIA / IDENTIDADE / WEBSITE',title:'Precisão com sensibilidade.',main:'stival.webp',detail:'brand/stival-10.png',bg:'#d7d9cb'},
{id:'marcen',name:'Marcen',label:'IDENTIDADE / WEBSITE / ERP',title:'Da oficina à entrega.',main:'marcen.webp',detail:'brand/marcen-aplicacoes.png',bg:'#d1d8c0'},
{id:'recebidos',name:'Recebidos do Bem',label:'IDENTIDADE / CAMPANHA / SISTEMA',title:'Um gesto que vira identidade.',main:'recebidos.webp',detail:'recebidos-aplicacoes.webp',bg:'#ddd2bf'},
{id:'cuqui',name:'CUQUI',label:'DIREÇÃO VISUAL / EXPERIÊNCIA DIGITAL',title:'Personalidade em cada detalhe.',main:'cuqui.webp',detail:'brand/cuqui-cookie-assorted.jpg',bg:'#d3cec0'},
{id:'tidle',name:'TIDLE',label:'IDENTIDADE / UNIVERSO DIGITAL',title:'Um universo para explorar.',main:'brand/tidle-cinematic.png',detail:'brand/tidle-hunt-amazon.png',bg:'#c9cebd'}
];
type Project=typeof projects[number];
const Film:React.FC<{project:Project}>=({project:p})=>{const frame=useCurrentFrame();const [handle]=useState(()=>delayRender('Font'));useEffect(()=>{document.fonts.load('500 20px Space').then(()=>continueRender(handle)).catch(()=>continueRender(handle))},[handle]);const mix=interpolate(frame,[0,72,94,153,179],[0,0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const drift=Math.sin(frame/180*Math.PI*2)*5;return <AbsoluteFill style={{background:'#edede5',color:'#242520',fontFamily:'Space,sans-serif'}}><style>{`@font-face{font-family:Space;src:url('${staticFile('fonts/SpaceGrotesk.ttf')}');font-weight:300 700}`}</style><div style={{position:'absolute',left:50,right:50,top:34,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:30,fontWeight:700,letterSpacing:-2.3}}>romeiro<span style={{fontSize:10,verticalAlign:'top',marginLeft:5}}>✳</span></div><div style={{fontSize:11,letterSpacing:1.4}}>{p.label}</div></div><div style={{position:'absolute',left:50,right:50,top:98,display:'flex',alignItems:'end',justifyContent:'space-between',paddingBottom:22,borderBottom:'1px solid #24252033'}}><div style={{fontSize:p.name.length>12?54:66,lineHeight:1,fontWeight:500,letterSpacing:-4}}>{p.name}</div><div style={{fontSize:17,letterSpacing:-.5,paddingBottom:4}}>{p.title}</div></div><div style={{position:'absolute',left:50,right:50,top:220,bottom:62,background:p.bg,overflow:'hidden'}}><div style={{position:'absolute',inset:0,opacity:1-mix,display:'flex',alignItems:'center',justifyContent:'center',padding:'30px 90px',transform:`translateY(${drift}px)`}}><Img src={staticFile('cases/'+p.main)} style={{width:'100%',height:'100%',objectFit:'contain',boxShadow:'0 10px 30px #24252014'}}/></div><div style={{position:'absolute',inset:0,opacity:mix,display:'flex',alignItems:'center',justifyContent:'center',gap:24,padding:30,background:'#242820',transform:`translateY(${-drift}px)`}}><Img src={staticFile('cases/'+p.main)} style={{width:'52%',height:'100%',objectFit:'contain'}}/><Img src={staticFile('cases/'+p.detail)} style={{width:'45%',height:'100%',objectFit:'contain'}}/></div></div><div style={{position:'absolute',left:50,right:50,bottom:24,display:'flex',justifyContent:'space-between',fontSize:9,letterSpacing:1.5}}><span>VINICIUS ROMEIRO × INOVASYS</span><span>ESTÉTICA. LÓGICA. INTENÇÃO.</span></div></AbsoluteFill>};
registerRoot(()=> <>{projects.map(project=><Composition key={project.id} id={`V2-${project.id}`} component={Film} defaultProps={{project}} durationInFrames={180} fps={30} width={1280} height={800}/>)}</>);
